package Ejercicio13;
@startuml

class Persona {
    - nombre : String
    - edad : int
    + mostrarDatos()
}

class Estudiante {
    - carnet : String
    - carrera : String
    + estudiar()
}

class Curso {
    - nombre : String
    - codigo : String
    + mostrarCurso()
}

Persona <|-- Estudiante
Estudiante "0..*" -- "1..*" Curso

@enduml